print("=========成绩录入=========")
name1=input("姓名1：")
score1=input("成绩1：")
name2=input("姓名2：")
score2=input("成绩2：")
name3=input("姓名3：")
score3=input("成绩3：")
name4=input("姓名4：")
score4=input("成绩4:")
print("\n本小组的成绩录入如下：")
print("序号         "f"{'姓名':<10}{'成绩':<10}")
print("1            "f"{name1:<10}  {score1:<10}")
print("2            "f"{name2:<10}  {score2:<10}")
print("3            "f"{name3:<10}  {score3:<10}")
print("4            "f"{name4:<10}  {score4:<10}")
scores=(score1,score2,score3,score4)
zuigao=max(scores)
if(zuigao==score1):
    print("本小组的最好成绩同学为：",name1,score1)
elif(zuigao==score2):
    print("本小组的最好成绩同学为：",name2,score2)
elif(zuigao==score3):
    print("本小组的最好成绩同学为：",name3,score3)
else:
    print("本小组的最好成绩同学为：",name4,score4)
